In [2]:
import pandas as pd
import numpy as np

In [3]:
recipes = pd.read_csv('recipes1.csv')
reviews = pd.read_csv('reviews1.csv')

In [16]:
recipes.loc[recipes.Name == 'Baked Italian Meatballs' , 'RecipeId']

79928      84957
220507    229849
Name: RecipeId, dtype: int64

In [14]:
pd.set_option('display.max_colwidth', None)

In [17]:
recipes.loc[recipes.RecipeId == 84957 , 'RecipeInstructions']

79928    c("Preheat oven to 400 F.", "Spray a broiler pan with broiling rack well with nonstick spray (I line the bottom part with foil and then spray).", "Combine all ingredients well.", "Form into 30 meatballs using a 1 1/2\" diameter scoop (or use your hands).", "Set on sprayed broiler rack in prepared pan and bake for 15-20 minutes, or until meatballs are cooked through.", "Add these meatballs to your favorite sauce and serve over pasta or in a hoagie roll with sauce& cheese to make a great sandwich."\n)
Name: RecipeInstructions, dtype: object

In [11]:
recipes.head()

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions,NumofRatings
0,38,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,PT24H,PT45M,PT24H45M,1999-08-09T21:46:00Z,Make and share this Low-Fat Berry Blue Frozen ...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan...",4
1,39,Biryani,1567,elly9812,PT25M,PT4H,PT4H25M,1999-08-29T13:12:00Z,Make and share this Biryani recipe from Food.com.,"c(""https://img.sndimg.com/food/image/upload/w_...",...,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and...",1
2,40,Best Lemonade,1566,Stephen Little,PT5M,PT30M,PT35M,1999-09-05T19:52:00Z,This is from one of my first Good House Keepi...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ...",9
3,41,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,PT20M,PT24H,PT24H20M,1999-09-03T14:54:00Z,This dish is best prepared a day in advance to...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"c(""Drain the tofu, carefully squeezing out exc...",2
4,42,Cabbage Soup,1538,Duckie067,PT30M,PT20M,PT50M,1999-09-19T06:19:00Z,Make and share this Cabbage Soup recipe from F...,"""https://img.sndimg.com/food/image/upload/w_55...",...,0.0,959.3,25.1,4.8,17.7,4.3,4.0,NaN,"c(""Mix everything together and bring to a boil...",9

In [6]:
recipes.iloc[0]

RecipeId                                                                     38
Name                                          Low-Fat Berry Blue Frozen Dessert
AuthorId                                                                   1533
AuthorName                                                               Dancer
CookTime                                                                  PT24H
PrepTime                                                                  PT45M
TotalTime                                                              PT24H45M
DatePublished                                              1999-08-09T21:46:00Z
Description                   Make and share this Low-Fat Berry Blue Frozen ...
Images                        c("https://img.sndimg.com/food/image/upload/w_...
RecipeCategory                                                  Frozen Desserts
Keywords                      c("Dessert", "Low Protein", "Low Cholesterol",...
RecipeIngredientQuantities                              c("4", "1/4", "1", "1")
RecipeIngredientParts         c("blueberries", "granulated sugar", "vanilla ...
AggregatedRating                                                            4.5
Calories                                                                  170.9
FatContent                                                                  2.5
SaturatedFatContent                                                         1.3
CholesterolContent                                                            8
SodiumContent                                                              29.8
CarbohydrateContent                                                        37.1
FiberContent                                                                3.6
SugarContent                                                               30.2
ProteinContent                                                              3.2
RecipeServings                                                                4
RecipeYield                                                                 NaN
RecipeInstructions            c("Toss 2 cups berries with sugar.", "Let stan...
NumofRatings                                                                  4
Name: 0, dtype: object

In [7]:
reviews.head()

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted
0,2,992,2008,gayg msft,5,better than any you can get at a restaurant!,2000-01-25T21:44:00Z
1,7,4384,1634,Bill Hilbrich,4,"I cut back on the mayo, and made up the differ...",2001-10-17T16:49:59Z
2,9,4523,2046,Gay Gilmore ckpt,2,i think i did something wrong because i could ...,2000-02-25T09:00:00Z
3,13,7435,1773,Malarkey Test,5,easily the best i have ever had. juicy flavor...,2000-03-13T21:15:00Z
4,14,44,2085,Tony Small,5,An excellent dish.,2000-03-28T12:51:00Z

In [8]:
reviews.iloc[0]

ReviewId                                                    2
RecipeId                                                  992
AuthorId                                                 2008
AuthorName                                          gayg msft
Rating                                                      5
Review           better than any you can get at a restaurant!
DateSubmitted                            2000-01-25T21:44:00Z
Name: 0, dtype: object

# Pre-processing

Drop columns ,reduce rows, and join reviews

In [9]:
# limit recipe entries
recipes_df = recipes
reviews_df = reviews
# extract rows with reviews
recipes_df = pd.DataFrame.merge(recipes_df, reviews_df.RecipeId, on='RecipeId').drop_duplicates('RecipeId')

# Delete rows with null values

In [10]:
recipes_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 271674 entries, 0 to 1401962
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   RecipeId                    271674 non-null  int64
 1   Name                        271674 non-null  object
 2   AuthorId                    271674 non-null  int64
 3   AuthorName                  271674 non-null  object
 4   CookTime                    228628 non-null  object
 5   PrepTime                    271674 non-null  object
 6   TotalTime                   271674 non-null  object
 7   DatePublished               271674 non-null  object
 8   Description                 271671 non-null  object
 9   Images                      271673 non-null  object
 10  RecipeCategory              271425 non-null  object
 11  Keywords                    265248 non-null  object
 12  RecipeIngredientQuantities  271672 non-null  object
 13  RecipeIngredientParts       271674 non-null  object
 14  AggregatedRating            265982 non-null  float64
 15  Calories                    271674 non-null  float64
 16  FatContent                  271674 non-null  float64
 17  SaturatedFatContent         271674 non-null  float64
 18  CholesterolContent          271674 non-null  float64
 19  SodiumContent               271674 non-null  float64
 20  CarbohydrateContent         271674 non-null  float64
 21  FiberContent                271674 non-null  float64
 22  SugarContent                271674 non-null  float64
 23  ProteinContent              271674 non-null  float64
 24  RecipeServings              173683 non-null  float64
 25  RecipeYield                 84104 non-null   object
 26  RecipeInstructions          271674 non-null  object
 27  NumofRatings                271674 non-null  int64
dtypes: float64(11), int64(3), object(14)
memory usage: 60.1+ MB

In [11]:
recipes_df = recipes_df.dropna()
recipes_df = recipes_df[recipes_df.Images != 'character(0)']
recipes_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15390 entries, 14 to 1401935
Data columns (total 28 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   RecipeId                    15390 non-null  int64
 1   Name                        15390 non-null  object
 2   AuthorId                    15390 non-null  int64
 3   AuthorName                  15390 non-null  object
 4   CookTime                    15390 non-null  object
 5   PrepTime                    15390 non-null  object
 6   TotalTime                   15390 non-null  object
 7   DatePublished               15390 non-null  object
 8   Description                 15390 non-null  object
 9   Images                      15390 non-null  object
 10  RecipeCategory              15390 non-null  object
 11  Keywords                    15390 non-null  object
 12  RecipeIngredientQuantities  15390 non-null  object
 13  RecipeIngredientParts       15390 non-null  object
 14  AggregatedRating            15390 non-null  float64
 15  Calories                    15390 non-null  float64
 16  FatContent                  15390 non-null  float64
 17  SaturatedFatContent         15390 non-null  float64
 18  CholesterolContent          15390 non-null  float64
 19  SodiumContent               15390 non-null  float64
 20  CarbohydrateContent         15390 non-null  float64
 21  FiberContent                15390 non-null  float64
 22  SugarContent                15390 non-null  float64
 23  ProteinContent              15390 non-null  float64
 24  RecipeServings              15390 non-null  float64
 25  RecipeYield                 15390 non-null  object
 26  RecipeInstructions          15390 non-null  object
 27  NumofRatings                15390 non-null  int64
dtypes: float64(11), int64(3), object(14)
memory usage: 3.4+ MB

# Clean the following columns:
Keywords, RecipeIngredientQuantities, RecipeIngredientParts, RecipeInstructions

In [12]:
import re

def map_str_to_list(string):
    #pattern = re.compile(r'\"(.+)\"')
    pattern = re.compile(r'\"([^"]+)\"')
    return pattern.findall(string)

def map_for_series(series: pd.Series):
    return series.apply(lambda i: map_str_to_list(i))

In [13]:
modify_col_list = ['Images','Keywords', 'RecipeIngredientQuantities', 'RecipeIngredientParts', 'RecipeInstructions']
recipes_df = recipes_df.apply(lambda x: map_for_series(x) if x.name in modify_col_list else x)

# Remove single quotes from start and end in Description column:

In [14]:
for i in recipes_df.Description:
    if i.startswith("'"):
        print(recipes_df.loc[recipes_df.Description == i, 'RecipeId'])
    elif i.endswith("'"):
        print('endswith')
        print(recipes_df.loc[recipes_df.Description == i, 'RecipeId'])
        print('endswith')

endswith
759850    124275
Name: RecipeId, dtype: int64
endswith
1332890    423347
Name: RecipeId, dtype: int64
1381051    485183
Name: RecipeId, dtype: int64

In [15]:
recipes_df.loc[recipes_df.RecipeId == 124275 , 'Description'] = recipes_df.loc[recipes_df.RecipeId == 124275, 'Description'].str[:-1]

In [16]:
recipes_df.loc[recipes_df.RecipeId == 423347 , 'Description'] = recipes_df.loc[recipes_df.RecipeId == 423347 , 'Description'].str[1:]

In [17]:
recipes_df.loc[recipes_df.RecipeId == 485183 , 'Description'] = recipes_df.loc[recipes_df.RecipeId == 485183 , 'Description'].str[1:]

# Remove single quotes from start and end in Name column:

In [18]:
for i in recipes_df.Name:
    if i.startswith("'"):
        print(recipes_df.loc[recipes_df.Name == i, 'RecipeId'])
    elif i.endswith("'"):
        print('endswith')
        print(recipes_df.loc[recipes_df.Name == i, 'RecipeId'])
        print('endswith')

endswith
875754    159060
Name: RecipeId, dtype: int64
endswith
endswith
1155363    288334
Name: RecipeId, dtype: int64
endswith
1249068    350400
Name: RecipeId, dtype: int64
endswith
1363767    459830
Name: RecipeId, dtype: int64
endswith

In [19]:
recipes_df.loc[recipes_df.RecipeId == 159060 , 'Name'] = recipes_df.loc[recipes_df.RecipeId == 159060, 'Name'].str[:-1]

In [20]:
recipes_df.loc[recipes_df.RecipeId == 288334 , 'Name'] = recipes_df.loc[recipes_df.RecipeId == 288334, 'Name'].str[:-1]

In [21]:
recipes_df.loc[recipes_df.RecipeId == 459830 , 'Name'] = recipes_df.loc[recipes_df.RecipeId == 459830, 'Name'].str[:-1]

In [22]:
recipes_df.loc[recipes_df.RecipeId == 350400 , 'Name'] = recipes_df.loc[recipes_df.RecipeId == 350400, 'Name'].str[1:]

# Remove single quotes from start and end in RecipeYield column:

In [23]:
for i in recipes_df.RecipeYield:
    if i.startswith("'"):
        print(recipes_df.loc[recipes_df.RecipeYield == i, 'RecipeId'])
    elif i.endswith("'"):
        print('endswith')
        print(recipes_df.loc[recipes_df.RecipeYield == i, 'RecipeId'])
        print('endswith')

endswith
49886    9770
Name: RecipeId, dtype: int64
endswith
endswith
780915    130876
Name: RecipeId, dtype: int64
endswith
endswith
1155363    288334
Name: RecipeId, dtype: int64
endswith
endswith
1307019    396411
Name: RecipeId, dtype: int64
endswith
endswith
1349221    442055
Name: RecipeId, dtype: int64
endswith

In [24]:
recipes_df.loc[recipes_df.RecipeId == 9770 , 'RecipeYield'] = recipes_df.loc[recipes_df.RecipeId == 9770, 'RecipeYield'].str[:-1]

In [25]:
recipes_df.loc[recipes_df.RecipeId == 130876 , 'RecipeYield'] = recipes_df.loc[recipes_df.RecipeId == 130876, 'RecipeYield'].str[:-1]

In [26]:
recipes_df.loc[recipes_df.RecipeId == 288334 , 'RecipeYield'] = recipes_df.loc[recipes_df.RecipeId == 288334, 'RecipeYield'].str[:-1]

In [27]:
recipes_df.loc[recipes_df.RecipeId == 396411 , 'RecipeYield'] = recipes_df.loc[recipes_df.RecipeId == 396411, 'RecipeYield'].str[:-1]

In [28]:
recipes_df.loc[recipes_df.RecipeId == 442055 , 'RecipeYield'] = recipes_df.loc[recipes_df.RecipeId == 442055, 'RecipeYield'].str[:-1]

In [29]:
recipes_df.head(4)

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions,NumofRatings
14,41,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,PT20M,PT24H,PT24H20M,1999-09-03T14:54:00Z,This dish is best prepared a day in advance to...,[https://img.sndimg.com/food/image/upload/w_55...,...,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"[Drain the tofu, carefully squeezing out exces...",2
81,54,Carrot Cake,1535,Marg CaymanDesigns,PT50M,PT45M,PT1H35M,1999-09-13T15:20:00Z,This is one of the few recipes my husband ever...,[https://img.sndimg.com/food/image/upload/w_55...,...,69.8,534.8,67.0,1.6,47.9,5.0,12.0,1 bundt,"[Beat together the eggs, oil, and white sugar....",17
947,168,Anzac Biscuits,1775,kitka9,PT15M,PT10M,PT25M,1999-08-19T05:14:00Z,These biscuits (cookies in America) are called...,[https://img.sndimg.com/food/image/upload/w_55...,...,22.3,143.4,25.0,1.5,10.9,2.2,12.0,12-24 cookies,"[Mix oats, flour, sugar and coconut together.,...",32
1072,187,Chicken-Fried Steak With Cracked Pepper Gravy,275742,bugsbunnyfan,PT15M,PT1H20M,PT1H35M,1999-09-12T06:23:00Z,Make and share this Chicken-Fried Steak With C...,[https://img.sndimg.com/food/image/upload/w_55...,...,241.1,1017.8,46.0,1.9,0.3,32.9,4.0,3 cups,[Prepare the flour spice by blending the flour...,9

# Pre-process reviews dataset

In [30]:
reviews_df = pd.DataFrame.merge(reviews_df, recipes_df.RecipeId, how= 'inner')

In [31]:
reviews_df

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted
0,50,1078,2639,Elisabeth Summers,5,"Your recipe was wonderful, it all fit together...",2000-09-20T14:09:06Z
1,2002,1078,13879,Leslie,5,"Little prep time, and delicious! I used the s...",2001-08-06T12:25:09Z
2,10534,1078,31803,Carolyn Kamberlane,5,I served this at a dinner party along with tor...,2002-03-22T13:52:51Z
3,13533,1078,4470,Bergy,5,Just right with 3 jalapenos and I used 3 tbsp ...,2002-05-06T16:21:17Z
4,19051,1078,41735,Chef Jan,3,I have found most people like this with less j...,2002-07-14T15:54:42Z
...,...,...,...,...,...,...,...
111985,2089715,507549,109030,Linajjac,5,Great recipe! I did add roasted garlic &amp; P...,2020-12-11T05:04:02Z
111986,2089823,533195,128473,Baby Kato,5,Yummy,2020-12-14T17:05:50Z
111987,2089916,317009,2321218,lindaversluis,5,"we enjoyed this very much, but be very careful...",2020-12-17T10:21:02Z
111988,2089992,379694,2002890888,harvelconsulting,5,"As a Kansas City native, making this savory ch...",2020-12-19T20:44:39Z
111989,2090176,374605,2500830,Shockeroo,5,I have made this recipe probably 20 times. It ...,2020-12-24T03:39:54Z

In [33]:
reviews_df.DateSubmitted = reviews_df.DateSubmitted.str[:-1]

In [34]:
reviews_df

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted
0,50,1078,2639,Elisabeth Summers,5,"Your recipe was wonderful, it all fit together...",2000-09-20T14:09:06
1,2002,1078,13879,Leslie,5,"Little prep time, and delicious! I used the s...",2001-08-06T12:25:09
2,10534,1078,31803,Carolyn Kamberlane,5,I served this at a dinner party along with tor...,2002-03-22T13:52:51
3,13533,1078,4470,Bergy,5,Just right with 3 jalapenos and I used 3 tbsp ...,2002-05-06T16:21:17
4,19051,1078,41735,Chef Jan,3,I have found most people like this with less j...,2002-07-14T15:54:42
...,...,...,...,...,...,...,...
111985,2089715,507549,109030,Linajjac,5,Great recipe! I did add roasted garlic &amp; P...,2020-12-11T05:04:02
111986,2089823,533195,128473,Baby Kato,5,Yummy,2020-12-14T17:05:50
111987,2089916,317009,2321218,lindaversluis,5,"we enjoyed this very much, but be very careful...",2020-12-17T10:21:02
111988,2089992,379694,2002890888,harvelconsulting,5,"As a Kansas City native, making this savory ch...",2020-12-19T20:44:39
111989,2090176,374605,2500830,Shockeroo,5,I have made this recipe probably 20 times. It ...,2020-12-24T03:39:54

In [36]:
reviews_df.Review = reviews_df.Review.str.replace("'", "")

In [63]:
recipes_df.CookTime = recipes_df.CookTime.str[2:]

In [64]:
recipes_df.PrepTime = recipes_df.PrepTime.str[2:]

In [65]:
recipes_df.TotalTime = recipes_df.TotalTime.str[2:]

In [66]:
recipes_df.DatePublished = recipes_df.DatePublished.str[:-1]

In [67]:
count = 0
for i in recipes.DatePublished:
    if not i.endswith('Z'):
        count = count + 1
print(count)

0

In [68]:
recipes_df.head(2)

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions,NumofRatings
14,41,Carina's Tofu-Vegetable Kebabs,1586,Cyclopz,20M,24H,24H20M,1999-09-03T14:54:00,This dish is best prepared a day in advance to...,[https://img.sndimg.com/food/image/upload/w_55...,...,0.0,1558.6,64.2,17.3,32.1,29.3,2.0,4 kebabs,"[Drain the tofu, carefully squeezing out exces...",2
81,54,Carrot Cake,1535,Marg CaymanDesigns,50M,45M,1H35M,1999-09-13T15:20:00,This is one of the few recipes my husband ever...,[https://img.sndimg.com/food/image/upload/w_55...,...,69.8,534.8,67.0,1.6,47.9,5.0,12.0,1 bundt,"[Beat together the eggs, oil, and white sugar....",17